---


- name: Print architecture variables
  ansible.builtin.debug:
    msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}, Distro: {{ ansible_distribution }}, DPKG_arch: {{ arch_mapping[ansible_architecture] | default(ansible_architecture) }} "

- name: Update and upgrade all packages to the latest version
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common

- name: Add Docker repo using key from URL
  deb822_repository:
    name: docker
    types: deb
    uris:  https://download.docker.com/linux/{{ ansible_distribution | lower }}
    suites: '{{ ansible_distribution_release }}'
    components: stable
    architectures: "{{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}" # amd64 or aarch64
    signed_by:  https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg


# name: Create directory for Docker's GPG key
# ansible.builtin.file:
#   path: /etc/apt/keyrings
#   state: directory
#   mode: '0755'

# name: Add Docker's official GPG key
# ansible.builtin.apt_key:
#   url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
#   keyring: /etc/apt/keyrings/docker.asc
#   state: present

# name: Print architecture variables
# ansible.builtin.debug:
#   msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}, Distro: {{ ansible_distribution }}"

# name: Add Docker repository
# ansible.builtin.apt_repository:
#   repo: >-
#     deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
#     signed-by=/etc/apt/keyrings/docker.gpg]
#     https://download.docker.com/linux/{{ ansible_distribution }} {{ ansible_lsb.codename }} stable
#   filename: docker
#   state: present


# name: Add Docker repository
# ansible.builtin.apt_repository:
#   repo: >-
#     deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }} signed-by=/etc/apt/keyrings/docker.gpg] 
#     https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
#   filename: docker
#   state: present

- name: Install Docker and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
#   update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  become: true

- name: Add Docker group if not already present
  ansible.builtin.group:
    name: docker
    state: present

- name: Add {{ docker_user }} to Docker group
  ansible.builtin.user:
    name: "{{ docker_user }}" 
    groups: docker
    append: true

- name: Enable and start Docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service

