---
# defaults file for docker

docker_user: "{{ system_account.name }}"

# Where you want Docker to store images
# Keep this on a fast disk, ideally an SSD. It doesn't need to be backed up.
docker_image_directory: "/var/lib/docker"

# Docker storage driver, see https://docs.docker.com/storage/storagedriver/select-storage-driver/#supported-backing-filesystems
# You might want to change this to ZFS, depending on your underlying filesystem.
docker_storage_driver: overlay2

docker_daemon_json:
  data-root: "{{ docker_image_directory }}"
  storage-driver: "{{ docker_storage_driver }}"

vars:
  arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
    x86_64: amd64
    aarch64: arm64
